#!/usr/bin/env bash
set -euo pipefail
APP_NAME="pexip-event-sink"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Please run as root: sudo ./uninstall.sh"
  exit 1
fi

PURGE="false"
if [[ "${1:-}" == "--purge" ]]; then
  PURGE="true"
fi

systemctl disable --now "$APP_NAME" 2>/dev/null || true
rm -f "/etc/systemd/system/${APP_NAME}.service"
systemctl daemon-reload

rm -f "/etc/apache2/conf-available/${APP_NAME}.conf" \
      "/etc/apache2/conf-enabled/${APP_NAME}.conf" \
      "/etc/apache2/sites-available/${APP_NAME}.conf" \
      "/etc/apache2/sites-enabled/${APP_NAME}.conf" \
      "/etc/httpd/conf.d/${APP_NAME}.conf"

# Remove the self-signed certificate generated by this installer, if used.
rm -rf "/etc/ssl/${APP_NAME}" 2>/dev/null || true

systemctl restart apache2 2>/dev/null || systemctl restart httpd 2>/dev/null || true

echo "Removed systemd service and Apache config."

if [[ "$PURGE" == "true" ]]; then
  rm -rf "/opt/${APP_NAME}" "/etc/${APP_NAME}" "/var/lib/${APP_NAME}" "/var/log/${APP_NAME}.log"
  echo "Purged app files, environment file, SQLite database, and log file."
else
  echo "Kept: /opt/${APP_NAME}, /etc/${APP_NAME}, /var/lib/${APP_NAME}, /var/log/${APP_NAME}.log"
  echo "Run sudo ./uninstall.sh --purge to remove everything including the database and env file."
fi
